### ISSUE TITLE
PDF Piscine

### ISSUE THREAD

**Issue by hezirel** [waitForTheQ/piscine-epitech#1]
Hey man, can i get the subjects pdf from your piscine ? I'd like to test my knowledge and the few piscine subjects i read were really challenging and interesting. Don't wanna pay 7K€ just to access that tho

Thanks

**Comment by waitForTheQ** [comment]
hi bro,

https://github.com/valentin-b99/CPool

<3

**Comment by hezirel** [comment]
Thanks bro ! Really appreciate it. Good luck at epitech ;)
